"""added url table for normalization

Revision ID: 13b6e3f931a8
Revises: 4bb9efc81fef
Create Date: 2025-10-20 15:09:51.774826

"""
from alembic import op
import sqlalchemy as sa


revision = '13b6e3f931a8'
down_revision = '4bb9efc81fef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    op.create_index(op.f('ix_urls_url'), 'urls', ['url'], unique=True)
    op.add_column('visits', sa.Column('url_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_url_datetime'), table_name='visits')
    op.drop_index(op.f('ix_visits_url'), table_name='visits')
    op.create_index('idx_url_id_datetime', 'visits', ['url_id', 'datetime_visited'], unique=False)
    op.create_index(op.f('ix_visits_url_id'), 'visits', ['url_id'], unique=False)
    op.create_foreign_key(None, 'visits', 'urls', ['url_id'], ['id'])
    op.drop_column('visits', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_url_id'), table_name='visits')
    op.drop_index('idx_url_id_datetime', table_name='visits')
    op.create_index(op.f('ix_visits_url'), 'visits', ['url'], unique=False)
    op.create_index(op.f('idx_url_datetime'), 'visits', ['url', 'datetime_visited'], unique=False)
    op.drop_column('visits', 'url_id')
    op.drop_index(op.f('ix_urls_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###

