""""added indexes to visits by url"

Revision ID: 4bb9efc81fef
Revises: f0d834f79e2d
Create Date: 2025-10-20 11:55:19.361069

"""
from alembic import op
import sqlalchemy as sa


revision = '4bb9efc81fef'
down_revision = 'f0d834f79e2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

