"""initial migration

Revision ID: f0d834f79e2d
Revises: 
Create Date: 2025-10-19 14:47:41.786587

"""
from alembic import op
import sqlalchemy as sa


revision = 'f0d834f79e2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('datetime_visited', sa.DateTime(timezone=True), nullable=False),
    sa.Column('link_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_url_datetime', 'visits', ['url', 'datetime_visited'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_url'), 'visits', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_url'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index('idx_url_datetime', table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###

